export const settings = {
  all_oneway: false,
  bidirectional_network_types: ["walk"],
  cache_folder: "./cache",
  cache_only_mode: false,
  data_folder: "./data",
  default_access: '["access"!~"private"]',
  default_crs: "epsg:4326",
  doh_url_template: "https://8.8.8.8/resolve?name={hostname}",
  elevation_url_template:
    "https://maps.googleapis.com/maps/api/elevation/json?locations={locations}&key={key}",
  http_accept_language: "en",
  http_referer: "Tilerama (https://github.com/ciospettw/Tilerama)",
  http_user_agent: "Tilerama (https://github.com/ciospettw/Tilerama)",
  imgs_folder: "./images",
  log_file: false,
  log_filename: "tilerama",
  log_console: true,
  log_level: "INFO",
  log_name: "Tilerama",
  logs_folder: "./logs",
  max_query_area_size: 2500000000,
  nominatim_key: null as string | null,
  nominatim_url: "https://nominatim.openstreetmap.org/",
  overpass_memory: null as number | null,
  overpass_rate_limit: true,
  overpass_settings: "[out:json][timeout:{timeout}]{maxsize}",
  overpass_url: "https://overpass.kumi.systems/api",
  requests_kwargs: {} as Record<string, any>,
  requests_timeout: 180,
  use_cache: true,
  useful_tags_node: ["highway", "junction", "railway", "ref"],
  useful_tags_way: [
    "access",
    "area",
    "bridge",
    "est_width",
    "highway",
    "junction",
    "landuse",
    "lanes",
    "maxspeed",
    "name",
    "oneway",
    "ref",
    "service",
    "tunnel",
    "width",
  ],
};
